import type { Metadata } from "next"
import Navbar from "@/components/custom/Navbar"
import { ThemeProvider } from "@/components/theme-provider"
import { inter } from "@/lib/fonts"
import Footer from "@/components/custom/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <main
        className={` ${inter.className} relative min-h-screen w-full  antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </main>
    </ThemeProvider>
  )
}
